
1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions

In [15]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        if not employees:
            return 0
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

    def display_info(self):
        print(f"Name: {self.name}")
        print(f"Family: {self.family}")
        print(f"Salary: ${self.salary}")
        print(f"Department: {self.department}")


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits

    def display_info(self):
        super().display_info()
        print(f"Benefits: {self.benefits}")


# Create instances of Employee and FulltimeEmployee classes
employee1 = Employee("akansha", "boga", 500000, "IT")
employee2 = Employee("Divya", "Nair", 650000, "Managment")
fulltime_employee1 = FulltimeEmployee("jahnavi", "nambiar", 800000, "IT", "Health Insurance, 401k")
fulltime_employee2 = FulltimeEmployee("jilla", "jeshwanth", 750000, "IT", "Health Insurance, 401k")

# Display employee information
print("Employee 1:")
employee1.display_info()
print("\nEmployee 2:")
employee2.display_info()
print("\nFulltime Employee 1:")
fulltime_employee1.display_info()
print("\nFulltime Employee 2:")
fulltime_employee2.display_info()

# Calculate and display average salary
employees = [employee1, employee2, fulltime_employee]
avg_salary = Employee.average_salary(employees)
print(f"\nAverage Salary: ${avg_salary:.2f}")

# Display total number of employees
print(f"\nTotal number of employees: {Employee.employee_count}")

Employee 1:
Name: akansha
Family: boga
Salary: $500000
Department: IT

Employee 2:
Name: Divya
Family: Nair
Salary: $650000
Department: Managment

Fulltime Employee 1:
Name: jahnavi
Family: nambiar
Salary: $800000
Department: IT
Benefits: Health Insurance, 401k

Fulltime Employee 2:
Name: jilla
Family: jeshwanth
Salary: $750000
Department: IT
Benefits: Health Insurance, 401k

Average Salary: $633333.33

Total number of employees: 4


2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [16]:
import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range 1-20
array = np.random.uniform(1, 20, 20)

# Step 2: Reshape the array to 4 by 5
reshaped_array = array.reshape(4, 5)

# Step 3: Replace the max in each row by 0 (axis=1)
# First, we create a boolean mask where True indicates the maximum value in each row
max_replace = reshaped_array == np.max(reshaped_array, axis=1, keepdims=True)

# Then, we use this mask to replace the max values with 0
result = np.where(max_replace, 0, reshaped_array)

# Print the results
print("Original vector:")
print(array)
print("\nReshaped array (4x5):")
print(reshaped_array)
print("\nArray with max values replaced by 0 in each row:")
print(result)

Original vector:
[ 4.40370801  6.56732857 14.7376441  15.32430861  6.62390073  9.97821128
  7.8796367   7.536244    8.29364687 10.83556641 12.25832232 13.21598432
  5.68901374 19.57791514 14.27091992  9.4724292   8.63969777 14.45849125
  5.42395536 16.10533369]

Reshaped array (4x5):
[[ 4.40370801  6.56732857 14.7376441  15.32430861  6.62390073]
 [ 9.97821128  7.8796367   7.536244    8.29364687 10.83556641]
 [12.25832232 13.21598432  5.68901374 19.57791514 14.27091992]
 [ 9.4724292   8.63969777 14.45849125  5.42395536 16.10533369]]

Array with max values replaced by 0 in each row:
[[ 4.40370801  6.56732857 14.7376441   0.          6.62390073]
 [ 9.97821128  7.8796367   7.536244    8.29364687  0.        ]
 [12.25832232 13.21598432  5.68901374  0.         14.27091992]
 [ 9.4724292   8.63969777 14.45849125  5.42395536  0.        ]]
